Revert afl-cmin change because "none" also works

diff --git a/afl-cmin b/afl-cmin
--- a/afl-cmin
+++ b/afl-cmin
@@ -164,7 +164,8 @@ fi
 if [ ! "$MEM_LIMIT" = "none" ]; then
 
   if [ "$MEM_LIMIT" -lt "5" ]; then
-    echo "[-] Warning: dangerously low memory limit." 1>&2
+    echo "[-] Error: dangerously low memory limit." 1>&2
+    exit 1
   fi
 
 fi
